language: php

matrix:
  fast_finish: true
  include:
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: hhvm
  allow_failures:
    - php: hhvm

before_script:
 - composer install
 - wget https://scrutinizer-ci.com/ocular.phar

script:
  - phpunit

after_script:
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml